### ISSUE TITLE
 Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.

### ISSUE THREAD

**Issue by kamiyaowl** [kamiyaowl/ikanopu#24]
# Log

```
ikanopu_1  | Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
ikanopu_1  |  (Exception from HRESULT: 0x8007007E)
ikanopu_1  | *** An exception has occurred because of P/Invoke. ***
ikanopu_1  | Please check the following:
ikanopu_1  | (1) OpenCV's DLL files exist in the same directory as the executable file.
ikanopu_1  | (2) Visual C++ Redistributable Package has been installed.
ikanopu_1  | (3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.
ikanopu_1  |
ikanopu_1  | System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
ikanopu_1  |  (Exception from HRESULT: 0x8007007E)
ikanopu_1  |    at OpenCvSharp.NativeMethods.core_Mat_sizeof()
ikanopu_1  |    at OpenCvSharp.NativeMethods.TryPInvoke()
ikanopu_1  |
ikanopu_1  | Unhandled Exception: System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
ikanopu_1  |  (Exception from HRESULT: 0x8007007E)
ikanopu_1  | *** An exception has occurred because of P/Invoke. ***
ikanopu_1  | Please check the following:
ikanopu_1  | (1) OpenCV's DLL files exist in the same directory as the executable file.
ikanopu_1  | (2) Visual C++ Redistributable Package has been installed.
ikanopu_1  | (3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.
ikanopu_1  |
ikanopu_1  | System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
ikanopu_1  |  (Exception from HRESULT: 0x8007007E)
ikanopu_1  |    at OpenCvSharp.NativeMethods.core_Mat_sizeof()
ikanopu_1  |    at OpenCvSharp.NativeMethods.TryPInvoke() ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
ikanopu_1  |  (Exception from HRESULT: 0x8007007E)
ikanopu_1  |    at OpenCvSharp.NativeMethods.core_Mat_sizeof()
ikanopu_1  |    at OpenCvSharp.NativeMethods.TryPInvoke()
ikanopu_1  |    --- End of inner exception stack trace ---
ikanopu_1  |    at OpenCvSharp.NativeMethods.TryPInvoke()
ikanopu_1  |    at OpenCvSharp.NativeMethods..cctor()
ikanopu_1  |    --- End of inner exception stack trace ---
ikanopu_1  |    at OpenCvSharp.NativeMethods.core_Mat_new2(Int32 rows, Int32 cols, Int32 type)
ikanopu_1  |    at ikanopu.Service.ImageProcessingService.InitializeAsync(GlobalConfig config) in /src/ikanopu/Service/ImageProcessingService.cs:line 46
ikanopu_1  |    at ikanopu.Program.<Main>d__3.MoveNext() in /src/ikanopu/Program.cs:line 89
ikanopu_1  | --- End of stack trace from previous location where exception was thrown ---
ikanopu_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
ikanopu_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
ikanopu_1  |    at ikanopu.Program.<Main>(String[] args)
ikanopu_ikanopu_1 exited with code 139
```

**Comment by kamiyaowl** [comment]
Ubuntu 18.04 with LD_DEBUG=libs

```
#################################################
#                                               #
#                    ikanopu                    #
#   url: https://github.com/kamiyaowl/ikanopu   #
#                                               #
#################################################

      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so: error: symbol lookup error: undefined symbol: PAL_lstrlenA (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so: error: symbol lookup error: undefined symbol: PAL_WideCharToMultiByte (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_GetTimeZoneDisplayNameW (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_GetLocaleInfoIntW (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_GetLocaleInfoGroupingSizesW (fatal)
DiscordのBot用のトークンを入力してください(secret.jsonに保存されるだけなので心配しないで
>

      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_GetCalendarsW (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_GetLocaleTimeFormatW (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_GetCalendarInfoW (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_EnumCalendarInfoW (fatal)
[2019/02/05 22:18:18] DiscordTokenが指定されていないため、利用することができません。
      7483:	find library=OpenCvSharpExtern.so [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/OpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/OpenCvSharpExtern.so
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/OpenCvSharpExtern.so
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/OpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/OpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/OpenCvSharpExtern.so
      7483:	  trying file=/lib/OpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/OpenCvSharpExtern.so
      7483:	
      7483:	find library=libtesseract.so.4 [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/libtesseract.so.4
      7483:	  trying file=/usr/lib/libtesseract.so.4
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/libtesseract.so.4
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/libtesseract.so.4
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/libtesseract.so.4
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/libtesseract.so.4
      7483:	  trying file=/lib/libtesseract.so.4
      7483:	  trying file=/usr/lib/libtesseract.so.4
      7483:	
      7483:	find library=libOpenCvSharpExtern.so [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/libOpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/libOpenCvSharpExtern.so
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/libOpenCvSharpExtern.so
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/libOpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/libOpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/libOpenCvSharpExtern.so
      7483:	  trying file=/lib/libOpenCvSharpExtern.so
      7483:	  trying file=/usr/lib/libOpenCvSharpExtern.so
      7483:	
      7483:	find library=OpenCvSharpExtern [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/OpenCvSharpExtern
      7483:	  trying file=/usr/lib/OpenCvSharpExtern
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/OpenCvSharpExtern
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/OpenCvSharpExtern
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/OpenCvSharpExtern
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/OpenCvSharpExtern
      7483:	  trying file=/lib/OpenCvSharpExtern
      7483:	  trying file=/usr/lib/OpenCvSharpExtern
      7483:	
      7483:	find library=libOpenCvSharpExtern [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/libOpenCvSharpExtern
      7483:	  trying file=/usr/lib/libOpenCvSharpExtern
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/libOpenCvSharpExtern
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/libOpenCvSharpExtern
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/libOpenCvSharpExtern
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/libOpenCvSharpExtern
      7483:	  trying file=/lib/libOpenCvSharpExtern
      7483:	  trying file=/usr/lib/libOpenCvSharpExtern
      7483:	
Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory

Unhandled Exception:       7483:	find library=Microsoft.DiaSymReader.Native.amd64.dll [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so: error: symbol lookup error: undefined symbol: PAL_CoTaskMemAlloc (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so: error: symbol lookup error: undefined symbol: PAL_CoTaskMemFree (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so: error: symbol lookup error: undefined symbol: PAL_LocalAlloc (fatal)
      7483:	/home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/libcoreclr.so: error: symbol lookup error: undefined symbol: PAL_LocalFree (fatal)
      7483:	find library=Microsoft.DiaSymReader.Native.amd64.dll [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	
      7483:	find library=Microsoft.DiaSymReader.Native.amd64.dll [0]; searching
      7483:	 search path=/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	 search path=/usr/local/lib		(LD_LIBRARY_PATH)
      7483:	  trying file=/usr/local/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	 search cache=/etc/ld.so.cache
      7483:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      7483:	  trying file=/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/tls/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	  trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
      7483:	
System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 136
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.TryPInvoke() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 145
   at OpenCvSharp.NativeMethods..cctor() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 60
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.core_Mat_new2(Int32 rows, Int32 cols, Int32 type)
   at OpenCvSharp.Mat..ctor(Int32 rows, Int32 cols, MatType type) in C:\projects\opencvsharp\src\OpenCvSharp\Modules\core\Mat\Mat.cs:line 98
   at ikanopu.Service.ImageProcessingService.InitializeAsync(GlobalConfig config) in /home/user/Documents/ikanopu/ikanopu/Service/ImageProcessingService.cs:line 50
   at ikanopu.Program.Main(String[] args) in /home/user/Documents/ikanopu/ikanopu/Program.cs:line 97
   at ikanopu.Program.<Main>(String[] args)
      7438:	
      7438:	calling fini: /home/user/.dotnet/shared/Microsoft.NETCore.App/2.1.7/libhostpolicy.so [0]
      7438:	
      7438:	
      7438:	calling fini: /home/user/.dotnet/host/fxr/2.1.7/libhostfxr.so [0]

```
